name: Sync TCGCSV to Firestore

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios csv-parser firebase-admin

      - name: Write Firebase credentials
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_CREDENTIALS" > credentials.json

      - name: Run sync script
        run: node scripts/sync-to-firestore.cjs
